name: my-workflow

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: first-step
        run: |
          echo "Hello World"
          echo "This is the second step"