name: Python-CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Show Python version
        run: python --version

      - name: Run Tests
        run: python -m unittest discover -s . -p "test_*.py"

      - name: Notify Slack
        if: always()
        continue-on-error: true
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.GITHUBSLACK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: "Python-CI"
          SLACK_MESSAGE: |
            Workflow '${{ github.workflow }}' finished with status '${{ job.status }}'
            on branch '${{ github.ref_name }}'.
            Commit: '${{ github.sha }}'.
            Triggered by '${{ github.actor }}'.
